//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LoadMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LoadMgr), typeof(Manager));
		L.RegFunction("ReplaceScene", ReplaceScene);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReplaceScene(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LoadMgr obj = (LoadMgr)ToLua.CheckObject(L, 1, typeof(LoadMgr));
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.ReplaceScene(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

