-- Generated by github.com/davyxu/tabtoy
-- Version: 2.2.1

local tab = {
	Demo = {
		{ ID = 101, Name = "张三", Skills = { 1, 2, 3 }, Props = { { Hp= 3, Atk= 3 } } 	},
		{ ID = 102, Name = "李四", Skills = { 1, 2, 3 }, Props = { { Hp= 3, Atk= 3 } } 	}
	}

}


-- ID
tab.DemoByID = {}
for _, rec in pairs(tab.Demo) do
	tab.DemoByID[rec.ID] = rec
end

return tab